### PR TITLE
Add Cobalt DI Container to the benchmark test suite 

### PR DESCRIPTION
**Pull request by jshannon63**
Consider adding the cobalt container to your test suite. The test suite ran normally using the docker image on my local repo. Thanks.

### CODE REVIEW

**Comment by kocsismate** [comment]
Thank your for your patch! I'll generate the updated results very soon. :)

**Comment by kocsismate** [comment]
@jshannon63 I've just did it! Did you see similar results when you run the benchmark? Cobalt is really fast! :)

**Comment by jshannon63** [comment]
Yes, they look consistent with my results. Cobalt does particularly good in the prototype tests since I added my new technique of dependency caching. It is still quite new, so it must prove itself in the community. Thanks for offering your benchmarks.

**Comment by kocsismate** [comment]
Nice job! I'll have a look at the source code 😊

**Pull request merged**
