### PR TITLE
Upgrade to Symfony 4

### PR DESCRIPTION
**Pull request by theofidry**
As Symfony 4 is out I think it's best to switch to 4.x instead of 3.4@dev.

### CODE REVIEW

**Comment by kocsismate** [comment]
Yeah, thank you very much! I still only used 3.4 because last time I wanted to try an optimization (I believe this one: https://github.com/symfony/symfony/pull/25474) and I could only find it in the 3.4 dev branch back then.

**Comment by kocsismate** [comment]
@theofidry I was told months before that Symfony DI works best with lower-case definition ID-s. Is this still the case?

Because I had to change the container configuration while upgrading to v4 to use FQCN-s as definition ID-s as the previous config didn't work anymore: https://github.com/kocsismate/php-di-container-benchmarks/commit/0f5f111351045f384eb3829bccdf75122cd72a6a#diff-8acfe3ece5e377f24d9b270cef51a907L53

So could you tell me what the most optimal setup is for Symfony?

**Comment by theofidry** [comment]
I’m not sure, I think it should be ok in both cases :)

**Comment by kocsismate** [comment]
Ok then I won't try to change it. For the record this is the original discussion about the topic: https://github.com/kocsismate/php-di-container-benchmarks/pull/8

**Comment by theofidry** [comment]
Oh I see. Apparently the micro-optim is still valid: it's not faster with or without lower-case definition IDs, but it is if you respect the case as if it doesn't, Symfony DI will be able to find the service but has to do further lookups

**Pull request merged**
