### PR TITLE
Added ClanCats Container

### PR DESCRIPTION
**Pull request by mario-deluna**
Hello there, I wanted to add this container to the benchmark for a while now and finally have been able to do so. :) 

I hope the PR fits your contribution guidelines. 

Kind Regards Mario.

### CODE REVIEW

**Comment by kocsismate** [comment]
Hi @mario-deluna ,

I'm really sorry, but I can't include this DI Container into the benchmark. Totally coincidentally, I've just removed a bunch of containers, and I don't plan to add any new container, unless it's a very popular one.

Besides the popularity criteria, conformance to PSR-11 became a hard requirement due to the recent changes of the benchmark. As far as I saw, ClanCats doesn't implement this interface (although adding support wouldn't be difficult).

**Comment by mario-deluna** [comment]
@kocsismate Its your repo, you make the rules :) 

On one hand I can understand the PSR-11 requirement on the other I think the interface conformity of two methods should not matter in a benchmark. The [Dice Container](https://github.com/Level-2/Dice) does also not implement the PSR-11 Interface will it be removed to?

Can you put that popularity criteria into a number? I would argue that Zen and Chubby are about in the same user range. 

Have a nice rest of your weekend ;)

**Comment by kocsismate** [comment]
@mario-deluna I was very close to remove Dice as well, however I postponed this mainly because its author created the original DI Container benchmark which I refer to in the introduction section, so this container has historical significance (and a fair popularity). However, I'll remove it if won't receive maintenance on the long run (e.g. proper support for PHP 8).

> I would argue that Zen and Chubby are about in the same user range.

Yeah, I know! Of course Zen doesn't count, since it's my own DI Container  :) but I agree that Chubby is also a less popular one. Since I had included it not long ago, I didn't want to get rid of it yet, especially because it performs well on the tests. I couldn't put the criteria of inclusion into numbers though.

**Comment by mario-deluna** [comment]
> Yeah, I know! Of course Zen doesn't count, since it's my own DI Container :)

Ah, I did not catch that it is yours, fair enough :) 

--- 

CCC did also perform quite well ;) 

screen



But hey, maybe if the popularity grows I will try again next year.

**Pull request closed without merging**
