### PR TITLE
chubbyphp-add-prototype-factory

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by dominikzogg** [comment]
@kocsismate since version 1.1 my container supports prototypes

**Comment by kocsismate** [comment]
Thank you for the PR, I'll run a new benchmark in the coming days.

**Comment by dominikzogg** [comment]
@kocsismate thank you, it will be worse, but it was the "best" i could find supporting protototypes

**Comment by dominikzogg** [comment]
@kocsismate would love to see the results

**Comment by kocsismate** [comment]
Sorry, I'm having really busy days. I'll try to do this until tomorrow evening :)

**Comment by dominikzogg** [comment]
@kocsismate thank you in advance, hope you're situation gets more relaxed as soon as possible.

**Comment by kocsismate** [comment]
@dominikzogg Done! :) The results were very interesting indeed: Symfony had a huge performance decrease, so I filed an issue for them.

**Comment by dominikzogg** [comment]
@kocsismate mine is getting worse to, but was an expected tradeof

**Comment by dominikzogg** [comment]
@kocsismate thank you

**Pull request merged**
