### PR TITLE
Add Disco container to benchmark.

### PR DESCRIPTION
**Pull request by shochdoerfer**

### CODE REVIEW

**Comment by kocsismate** [comment]
Thank you! Please resolve the conflicts so I can accept the PR :)

**Comment by kocsismate** [comment]
@shochdoerfer Just a question: Why is the ocramius/proxy-manager package required by default (but I could mention your logger lib too)? I think they should be optional so if I want lazy loading/logging then I can require them. This is the case in PHP-DI too: http://php-di.org/doc/lazy-injection.html#installation

I am asking it because there is something after merging your PR I don't like: now I can't just composer update on my host machine where there is no PHP 7, I now have to use composer from the container.

**Comment by shochdoerfer** [comment]
Disco basically extends ocramius/proxy-manager, it is a fixed requirement, you cannot use Disco without it. Disco itself requires PHP 7 because we need the return type hint introduced with PHP 7 in the config. That is why you cannot use Disco with PHP 5. If you really, really need PHP 5 support you would need to downgrade to Disco version 0.4.0 but that version is not maintained any more.

**Comment by kocsismate** [comment]
Ok, it makes sense! I will stay with the current version!

**Pull request merged**
