### PR TITLE
Add ProxyAutoloader to Disco config

### PR DESCRIPTION
**Pull request by shochdoerfer**
By configuring the proxy autoloader Disco will not re-generate the cache files on every request.

### CODE REVIEW

**Comment by kocsismate** [comment]
Thank your for the quick PR! I am curious how much it improves Disco's performance!

Anyway, I prefer to put compiled containers in the "resource" directories in the repo because it is easier to analyze them like that. Would you mind if I changed the path of the generated container for Disco too?

**Comment by shochdoerfer** [comment]
Sure, not a problem. Go ahead. The change improved the performance a lot, using the stored configuration  helps even more. But somehow the results seem a bit random. Need to dig into the why a bit more.

**Comment by kocsismate** [comment]
Do you run the tests with Docker? Unfortunately, on my Mac they also seemed to be random, so I had to install PHP-FPM on my host machine. This way, results are much more in line to what I supposed.

**Comment by shochdoerfer** [comment]
Yes I did run the tests in Docker. Good to know that this might be "problematic" ;)

**Comment by kocsismate** [comment]
Yeah, it is a bit sad thing to learn :/ I will try to use another image, and in the worst case, update the read me :D

**Comment by kocsismate** [comment]
But in any case, it's good to see that the new config improved Disco's performance a lot!

**Pull request merged**
